export const PSEUDO_CLASSES = {
  active: 'active',
  // 'any-link': 'any-link',
  blank: 'blank',
  checked: 'checked',
  // 'current': 'current',
  // 'default': 'default',
  // 'defined': 'defined',
  disabled: 'disabled',
  // 'drop': 'drop',
  empty: 'empty',
  enabled: 'enabled',
  // 'first': 'first',
  'first-child': 'the first child of its parent',
  'first-of-type': 'the first of its type in its parent',
  // 'fullscreen': 'fullscreen',
  // 'future': 'future',
  focus: 'focused',
  // 'focus-visible': 'focus-visible',
  // 'focus-within': 'focus-within',
  // 'host': 'host',
  hover: 'hovered',
  // 'indeterminate': 'indeterminate',
  // 'in-range': 'in-range',
  invalid: 'invalid',
  'last-child': 'the last child of its parent',
  'last-of-type': 'the last of its type in its parent',
  // 'left': 'left',
  // 'link': 'link',
  // 'local-link': 'local-link',
  'only-child': 'the only child of its parent',
  'only-of-type': 'the only of its type in its parent',
  optional: 'optional',
  'out-of-range': 'out-of-range',
  // 'past': 'past',
  // 'placeholder-shown': 'placeholder-shown',
  'read-only': 'read-only',
  // 'read-write': 'read-write',
  required: 'required',
  // 'right': 'right',
  // 'root': 'root',
  // 'scope': 'scope',
  target: 'targeted',
  // 'target-within': 'target-within',
  // 'user-invalid': 'user-invalid',
  valid: 'valid',
  visited: 'visited',
}

export const UNIQUE_ELEMENTS = ['html', 'body', 'head']
