export const PSEUDO_CLASSES = {
  active: 'active',
  'any-link': 'a link (visited or not)',
  blank: 'blank',
  checked: 'checked',
  current: 'the current item in a set',
  default: 'the default item among its siblings',
  defined: 'defined',
  disabled: 'disabled',
  drop: 'a drag-and-drop target',
  empty: 'empty',
  enabled: 'enabled',
  first: 'the first one in its group',
  'first-child': 'the first child of its parent',
  'first-of-type': 'the first of its type in its parent',
  fullscreen: 'fullscreen',
  future: 'in the future relative to the current position',
  focus: 'focused',
  'focus-visible': 'focused in a way that should be visibly indicated',
  'focus-within': 'focused or containing a focused descendant',
  host: 'the host element of a shadow tree',
  hover: 'hovered',
  indeterminate: 'indeterminate',
  'in-range': 'in-range',
  invalid: 'invalid',
  lang: token => (token.data ? `in ‘${token.data}’` : null),
  'last-child': 'the last child of its parent',
  'last-of-type': 'the last of its type in its parent',
  left: 'on the left page',
  link: 'an unvisited link',
  'local-link': 'a link to the current document',
  'nth-child': 'the nth child (formula) of its parent',
  'nth-of-type': 'the nth of its type (formula) in its parent',
  'nth-last-child': 'the nth from the end child (formula) of its parent',
  'nth-last-of-type':
    'the nth of its type from the end (formula) in its parent',
  'only-child': 'the only child of its parent',
  'only-of-type': 'the only of its type in its parent',
  optional: 'optional',
  'out-of-range': 'out-of-range',
  past: 'in the past relative to the current position',
  'placeholder-shown': 'showing its placeholder',
  'read-only': 'read-only',
  'read-write': 'read-write',
  required: 'required',
  right: 'on the right page',
  root: 'the root element of the document',
  scope: 'the reference scope element',
  target: 'targeted',
  'target-within': 'targeted or containing the targeted element',
  'user-invalid': 'user-invalid',
  valid: 'valid',
  visited: 'visited',
}

export const PSEUDO_ELEMENTS = {
  after: '‘after’ pseudo-element',
  backdrop: 'backdrop',
  before: '‘before’ pseudo-element',
  'first-letter': 'first letter',
  'first-line': 'first line',
  marker: 'marker',
  placeholder: 'placeholder',
  selection: 'highlighted selection',
}

export const UNIQUE_ELEMENTS = ['html', 'body', 'head']

export const RELATIONSHIPS = ['descendant', 'child', 'sibling', 'adjacent']

export const DEFAULT_NODE = {
  attrs: [],
  classes: [],
  id: null,
  pseudoClasses: [],
  pseudoElements: [],
  relationship: null,
  tagName: null,
}
